// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5KR5OtXUVyx5K-lYZB0JZmO0pCw1pfl8',
    appId: '1:1063977879594:web:eaa36d5579781d18b19b53',
    messagingSenderId: '1063977879594',
    projectId: 'chat-practice2',
    authDomain: 'chat-practice2.firebaseapp.com',
    storageBucket: 'chat-practice2.firebasestorage.app',
    measurementId: 'G-HYY7KGNXBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuj_zfO2AQBjOcgeC7mEjHTgGD6WYnba0',
    appId: '1:1063977879594:android:38e45278f4289193b19b53',
    messagingSenderId: '1063977879594',
    projectId: 'chat-practice2',
    storageBucket: 'chat-practice2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHjqunvlijKhRoLVtR7P8Mtjddyuca8Q',
    appId: '1:1063977879594:ios:54b22a7e1e392619b19b53',
    messagingSenderId: '1063977879594',
    projectId: 'chat-practice2',
    storageBucket: 'chat-practice2.firebasestorage.app',
    iosClientId: '1063977879594-e41cm1ufu7rl1o3c0tsm3ldrmji0m8fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOHjqunvlijKhRoLVtR7P8Mtjddyuca8Q',
    appId: '1:1063977879594:ios:54b22a7e1e392619b19b53',
    messagingSenderId: '1063977879594',
    projectId: 'chat-practice2',
    storageBucket: 'chat-practice2.firebasestorage.app',
    iosClientId: '1063977879594-e41cm1ufu7rl1o3c0tsm3ldrmji0m8fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5KR5OtXUVyx5K-lYZB0JZmO0pCw1pfl8',
    appId: '1:1063977879594:web:34db0b177dfab632b19b53',
    messagingSenderId: '1063977879594',
    projectId: 'chat-practice2',
    authDomain: 'chat-practice2.firebaseapp.com',
    storageBucket: 'chat-practice2.firebasestorage.app',
    measurementId: 'G-HX8E12KGP5',
  );

}